/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_MWC_NODE_LIB__
#define __RUST_MWC_NODE_LIB__
#ifdef __cplusplus
extern "C" {
#endif

/** \brief
 *  Free process_mwc_node_request response string
 */
void
free_node_lib_string (
    char * s);

/** \brief
 *  Process mwc-node related call.
 *  Input: json stirng param
 *  return: json string as a result. Call process_mwc_node_request to release the memory
 */
char *
process_mwc_node_request (
    char const * input);


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  Register a callback and context pointer from C
 *  Note, Callback will get temprary string pointer, C code can't store it.
 */
void
register_lib_callback (
    char const * callback_name,
    int8_t const * (*cb)(void *, int8_t const *),
    void * ctx);

/** \brief
 *  Unregister the callback
 */
void
unregister_lib_callback (
    char const * callback_name);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_MWC_NODE_LIB__ */
