[package]
name = "mwc_gen_gen"
version = "0.0.1"
edition = "2018"
authors = ["Mwc Developers <info@mwc.mw>"]
description = "Utility to automate the generation of Mwc's genesis block"
license = "Apache-2.0"
repository = "https://github.com/mwcproject/mwc-node"
keywords = [ "crypto", "mwc", "mimblewimble" ]
readme = "README.md"

[[bin]]
name = "gen_gen"
path = "src/bin/gen_gen.rs"

[dependencies]
chrono = "0.4.4"
cuckoo_miner = "1.0.0"
curl = "0.4.19"
mwc_core = { path = "../../core" }
mwc_chain = { path = "../../chain" }
mwc_keychain = { path = "../../keychain" }
mwc_miner_plugin = "1.0.0"
mwc_store = { path = "../../store" }
mwc_util = { path = "../../util" }
mwc_wallet = { path = "../../wallet" }
rpassword = "2.0.0"
serde_json = "1"

[patch.crates-io]
mwc_api = { path = "../../api" }
mwc_core = { path = "../../core" }
mwc_chain = { path = "../../chain" }
mwc_keychain = { path = "../../keychain" }
mwc_util = { path = "../../util" }
mwc_wallet = { path = "../../wallet" }
