name: Continuous Integration
on: [push, pull_request]

jobs:
  linux-tests:
    name: Linux Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_args: [servers, chain, core, keychain, pool, p2p, src, api, util, store]
    steps:
      - uses: actions/checkout@v3
      - name: Test ${{ matrix.job_args }}
        working-directory: ${{ matrix.job_args }}
        run: |
          case "${{ matrix.job_args }}" in
            api|chain|core|pool|servers)
              cargo test --release --features test-support
              ;;
            *)
              cargo test --release
              ;;
          esac

  macos-tests:
    name: macOS Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests
        run: cargo test --release --all --features test-support

  windows-tests:
    name: Windows Tests
    runs-on: windows-2025
    env:
      ROARING_ARCH: x86-64-v2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests
        run: cargo test --release --all --features test-support
